changes to the student form
UlisesMercer9/experientya-api pull request #1
Opened 2023-06-23 02:28 UTC by FranciscoJSL

-Se agregaron migraciones para dejar algunos campos como nulos
-Se quitaron los campos en el formulario de registro
-Se quitaron las validaciones tanto en el frontend como en el backend
-Se agregó la vista previa de la foto de perfil del usuario

2023-06-23 02:39 UTC, HRAD-bit requested changes
Porfa revisa el comentario que te dejé acerca de las migraciones.
Muy buen trabajo carnal 🥳

2023-06-23 02:39 UTC, HRAD-bit commented on database/migrations/2023_06_19_233159_update_columns_to_users_table.php
> +            $table->foreignId('user_country_id')->nullable(false)->change();
Porfavor revisa _2022_10_07_200743_add_cv_id_to_user_skills_table.php_
Recomiendo borrar la llave foránea (index), después borrar la columna y por último volver a crearla

2023-06-23 05:10 UTC, FranciscoJSL commented on database/migrations/2023_06_19_233159_update_columns_to_users_table.php
> +            $table->foreignId('user_country_id')->nullable(false)->change();
Intente hacerlo se la siguiente forma pero no me sirve:

  // Delete keys
  $table->dropForeign('users_user_country_id_foreign');
  $table->dropColumn('user_country_id');

  $table->dropForeign('users_user_state_id_foreign');
  $table->dropColumn('user_state_id');

  $table->dropForeign('users_user_city_id_foreign');
  $table->dropColumn('user_city_id');
  // Add keys
  $table->foreignId('user_country_id');
  $table->foreign('user_country_id')->references('id')->on('countries')->onDelete('cascade');

  $table->foreignId('user_state_id');
  $table->foreign('user_state_id')->references('id')->on('states')->onDelete('cascade');

  $table->foreignId('user_city_id');
  $table->foreign('user_city_id')->references('id')->on('towns')->onDelete('cascade');

2023-06-27 05:25 UTC, FranciscoJSL commented
modifique la migración y ahora lo que hace en el rollback es eliminar la columna y crearla de nuevo

2023-06-28 02:40 UTC, HRAD-bit approved these changes

2023-06-28 02:43 UTC, merged